apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretForVolumeName }}
stringData:
  {{- if .Values.l2.jwtSecret.file }}
  {{ .Values.l2.jwtSecret.filename }}: {{ .Values.l2.jwtSecret.file }}
  {{- end }}

  {{- if .Values.rollupConfig.file }}
  {{ .Values.rollupConfig.filename }}: {{ .Values.rollupConfig.file }}
  {{- end }}

  {{- if .Values.p2p.priv.file }}
  {{ .Values.p2p.priv.filename }}: {{ .Values.p2p.priv.file }}
  {{- end }}
